name: Build-Windows-EXE

on:
  # 推 tag 才打包；想每次 push main 都跑，把 tags 改成 branches: [ main ]
  push:
    tags: ["v*"]
  workflow_dispatch:        # 也允许手动触发

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install requirements
      run: |
        python -m pip install -r requirements.txt
        # 再装 PaddleOCR，本身已在 requirements 锁版本也行，没锁就加 --no-deps
        python -m pip install paddleocr==2.6.1.3 --no-deps

    # 如果脚本里需要系统工具（如 tesseract / poppler），可在这一步用 choco 安装
    # - name: Install Tesseract (optional)
    #   run: choco install tesseract --version 5.3.3 -y


    - name: Build EXE with PyInstaller
      run:  pyinstaller compare_ocr.py  --onefile  --name compare_ocr  --collect-all paddleocr  --collect-all pillow  --collect-submodules tools  --collect-submodules tools.infer  --hidden-import PIL.ImageDraw  --hidden-import PIL.ImageFont  --hidden-import PIL.Image  --hidden-import fitz  --add-data "data.xlsx;."  --add-data "docs;docs"
    # ① 上传 CI Artifact，便于在 Actions 里下载
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: compare_ocr_exe
        path: dist/compare_ocr.exe

    # ② 如是 tag 触发，自动生成 Release 并附带 exe
    - name: Publish Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: dist/compare_ocr.exe
